### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by shaun-edwards** [andreasBihlmaier/industrial_calibration_helpers#1]
Is there a license that covers this repo?  If not, Apache 2.0 or BSD is preferred.  I'd like to pull these scripts into the ROS-Industrial calibration stack.

**Comment by andreasBihlmaier** [comment]
@shaun-edwards Thank you for the hint.
I marked everything as BSD licensed (either in package.xml or directly in source files):
https://github.com/andreasBihlmaier/industrial_calibration_helpers/commit/129d888712caf3121f1a5b18ac85dc05bdb6722f
